// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIjeaWnPt8abUTibjd00HCWGSbmyeAj3A',
    appId: '1:468292043778:web:08290041999e8e0ec1931b',
    messagingSenderId: '468292043778',
    projectId: 'todo-app-e39ba',
    authDomain: 'todo-app-e39ba.firebaseapp.com',
    storageBucket: 'todo-app-e39ba.appspot.com',
    measurementId: 'G-7ET6EER6SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvoUWN4_Zh4nG6zlP5GwfxAAbvLQohYsY',
    appId: '1:468292043778:android:f282e71f7b875339c1931b',
    messagingSenderId: '468292043778',
    projectId: 'todo-app-e39ba',
    storageBucket: 'todo-app-e39ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDukKoaGp12zY1dwvzpexAvrnlCR-kzYio',
    appId: '1:468292043778:ios:0f9445b6809696dfc1931b',
    messagingSenderId: '468292043778',
    projectId: 'todo-app-e39ba',
    storageBucket: 'todo-app-e39ba.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDukKoaGp12zY1dwvzpexAvrnlCR-kzYio',
    appId: '1:468292043778:ios:aa5a2589930082a8c1931b',
    messagingSenderId: '468292043778',
    projectId: 'todo-app-e39ba',
    storageBucket: 'todo-app-e39ba.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
